service: covid19-et

custom:
  settings:
    POSTS_TABLE: CommunityReports
    TRAVELERS_TABLE: TravelersReports

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.TRAVELERS_TABLE}'

functions:
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: /communityReport
          method: post
  getAllPosts:
    handler: handler.getAllPosts
    events:
      - http:
          path: /communityReports
          method: get
  getPosts:
    handler: handler.getPosts
    events:
      - http:
          path: /communityReports/{number}
          method: get
  getPost:
    handler: handler.getPost
    events:
      - http:
          path: /communityReport/{id}
          method: get
  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: /communityReport/{id}
          method: put
  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: /communityReport/{id}
          method: delete

  createTraveler:
    handler: handler.createTraveler
    events:
      - http:
          path: /travelerReport
          method: post
  getAllTravelers:
    handler: handler.getAllTravelers
    events:
      - http:
          path: /travelerReports
          method: get
  getTravelers:
    handler: handler.getTravelers
    events:
      - http:
          path: /travelerReports/{number}
          method: get
  getTraveler:
    handler: handler.getTraveler
    events:
      - http:
          path: /travelerReport/{id}
          method: get
  updateTraveler:
    handler: handler.updateTraveler
    events:
      - http:
          path: /travelerReport/{id}
          method: put
  deleteTraveler:
    handler: handler.deleteTraveler
    events:
      - http:
          path: /travelerReport/{id}
          method: delete

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'ID'
            AttributeType: 'N'
        KeySchema:
          - AttributeName: 'ID'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}
    TravelersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'ID'
            AttributeType: 'N'
        KeySchema:
          - AttributeName: 'ID'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.TRAVELERS_TABLE}
